# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-03 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200402_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='like',
            name='question',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='has_avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
