# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_like_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
