# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-07 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ask_n_answer', '0002_auto_20200407_2202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('profile', 'content_type', 'object_id')]),
        ),
    ]
